/**
 * Reverse referral map: body zone → muscles whose TPs refer there.
 * Built from clinical trigger point literature (Travell & Simons).
 * Each entry: { muscleId, tpId, description }
 */

export interface ReferralEntry {
  muscleId: string;
  tpId:     string;
  location: string; // where on the muscle the TP is
}

export interface ReferralZone {
  id:      string;
  label:   string;
  region:  'head' | 'face' | 'neck' | 'shoulder' | 'arm' | 'elbow' | 'wrist_hand' | 'chest' | 'abdomen' | 'thoracic' | 'lumbar' | 'hip' | 'hip_groin' | 'thigh' | 'knee' | 'lower_leg' | 'foot';
  view:    'front' | 'back' | 'both';
  entries: ReferralEntry[];
}

export const REFERRAL_ZONES: ReferralZone[] = [
  {
    id: 'head_temporal',
    label: 'Head — temporal / temple',
    region: 'head',
    view: 'front',
    entries: [
      { muscleId: 'trapezius_desc',         tpId: 'TP1', location: 'Upper fibres, mid-belly' },
      { muscleId: 'sternocleidomastoideus',  tpId: 'TP1', location: 'Sternal head' },
      { muscleId: 'suboccipitals',           tpId: 'TP1', location: 'Suboccipital triangle' },
      { muscleId: 'scaleni',                 tpId: 'TP1', location: 'Anterior scalene' },
      { muscleId: 'masseter',           tpId: 'TP1', location: 'Superficial belly, cheek' },
      { muscleId: 'temporalis',         tpId: 'TP1', location: 'Anterior temporal' },
      { muscleId: 'trapezius_desc',     tpId: 'TP1', location: 'Upper fibres, mid-belly' },
    ],
  },
  {
    id: 'head_occipital',
    label: 'Head — occiput / base of skull',
    region: 'head',
    view: 'back',
    entries: [
      { muscleId: 'trapezius_desc',         tpId: 'TP2', location: 'Cervical attachment' },
      { muscleId: 'suboccipitals',           tpId: 'TP1', location: 'Suboccipital triangle' },
      { muscleId: 'sternocleidomastoideus',  tpId: 'TP1', location: 'Sternal head' },
      { muscleId: 'levator_scapulae',        tpId: 'TP1', location: 'Superior scapular angle' },
    ],
  },
  {
    id: 'head_eye',
    label: 'Head — around the eye',
    region: 'head',
    view: 'front',
    entries: [
      { muscleId: 'sternocleidomastoideus',  tpId: 'TP1', location: 'Sternal head' },
      { muscleId: 'suboccipitals',           tpId: 'TP1', location: 'Suboccipital triangle' },
      { muscleId: 'trapezius_desc',          tpId: 'TP1', location: 'Upper fibres' },
      { muscleId: 'masseter',           tpId: 'TP2', location: 'Deep belly, near ear' },
      { muscleId: 'temporalis',         tpId: 'TP2', location: 'Mid temporal' },
    ],
  },
  {
    id: 'neck_posterior',
    label: 'Neck — posterior',
    region: 'neck',
    view: 'back',
    entries: [
      { muscleId: 'trapezius_desc',         tpId: 'TP2', location: 'Cervical attachment' },
      { muscleId: 'levator_scapulae',        tpId: 'TP1', location: 'Superior scapular angle' },
      { muscleId: 'levator_scapulae',        tpId: 'TP2', location: 'Cervical belly' },
      { muscleId: 'suboccipitals',           tpId: 'TP1', location: 'Suboccipital triangle' },
      { muscleId: 'scaleni',                 tpId: 'TP2', location: 'Middle scalene' },
      { muscleId: 'trapezius_trans',    tpId: 'TP1', location: 'Middle fibres' },
      { muscleId: 'trapezius_asc',      tpId: 'TP1', location: 'Inferior scapular angle' },
      { muscleId: 'sternocleidomastoideus', tpId: 'TP1', location: 'Sternal head' },
    ],
  },
  {
    id: 'neck_lateral',
    label: 'Neck — lateral / angle of neck',
    region: 'neck',
    view: 'front',
    entries: [
      { muscleId: 'levator_scapulae',        tpId: 'TP1', location: 'Superior scapular angle' },
      { muscleId: 'sternocleidomastoideus',  tpId: 'TP2', location: 'Clavicular head' },
      { muscleId: 'scaleni',                 tpId: 'TP1', location: 'Anterior scalene' },
      { muscleId: 'trapezius_desc',     tpId: 'TP1', location: 'Upper fibres, mid-belly' },
      { muscleId: 'sternocleidomastoideus', tpId: 'TP1', location: 'Sternal head' },
      { muscleId: 'infraspinatus',      tpId: 'TP1', location: 'Medial fossa infraspinata' },
    ],
  },
  {
    id: 'shoulder_anterior',
    label: 'Shoulder — anterior',
    region: 'shoulder',
    view: 'front',
    entries: [
      { muscleId: 'infraspinatus',           tpId: 'TP1', location: 'Medial fossa infraspinata' },
      { muscleId: 'pectoralis_major',        tpId: 'TP1', location: 'Clavicular head' },
      { muscleId: 'pectoralis_minor',        tpId: 'TP1', location: 'Coracoid process' },
      { muscleId: 'deltoideus',              tpId: 'TP1', location: 'Anterior deltoid' },
      { muscleId: 'subscapularis',           tpId: 'TP1', location: 'Axillary border' },
      { muscleId: 'scaleni',                 tpId: 'TP1', location: 'Anterior scalene' },
      { muscleId: 'biceps_brachii',     tpId: 'TP1', location: 'Mid-belly' },
      { muscleId: 'supraspinatus',      tpId: 'TP1', location: 'Mid-belly, supraspinous fossa' },
      { muscleId: 'serratus_anterior',  tpId: 'TP1', location: 'Lateral thorax' },
      { muscleId: 'teres_minor',        tpId: 'TP1', location: 'Posterior axilla' },
    ],
  },
  {
    id: 'shoulder_posterior',
    label: 'Shoulder — posterior / suprascapular',
    region: 'shoulder',
    view: 'back',
    entries: [
      { muscleId: 'trapezius_asc',           tpId: 'TP1', location: 'Inferior scapular angle' },
      { muscleId: 'trapezius_trans',         tpId: 'TP1', location: 'Middle fibres' },
      { muscleId: 'infraspinatus',           tpId: 'TP2', location: 'Lateral fossa infraspinata' },
      { muscleId: 'levator_scapulae',        tpId: 'TP2', location: 'Cervical belly' },
      { muscleId: 'subscapularis',      tpId: 'TP1', location: 'Axillary border' },
      { muscleId: 'teres_major',        tpId: 'TP1', location: 'Posterior axilla' },
      { muscleId: 'teres_minor',        tpId: 'TP1', location: 'Posterior axilla' },
      { muscleId: 'supraspinatus',      tpId: 'TP1', location: 'Mid-belly, supraspinous fossa' },
      { muscleId: 'deltoideus',         tpId: 'TP1', location: 'Posterior deltoid' },
      { muscleId: 'infraspinatus',      tpId: 'TP1', location: 'Medial fossa infraspinata' },
    ],
  },
  {
    id: 'scapula_medial',
    label: 'Scapula — medial border / interscapular',
    region: 'thoracic',
    view: 'back',
    entries: [
      { muscleId: 'trapezius_asc',           tpId: 'TP1', location: 'Inferior scapular angle' },
      { muscleId: 'trapezius_trans',         tpId: 'TP1', location: 'Middle fibres' },
      { muscleId: 'rhomboids',               tpId: 'TP1', location: 'Medial scapular border' },
      { muscleId: 'infraspinatus',           tpId: 'TP1', location: 'Medial fossa infraspinata' },
      { muscleId: 'serratus_anterior',       tpId: 'TP1', location: 'Lateral thorax' },
      { muscleId: 'levator_scapulae',   tpId: 'TP1', location: 'Superior scapular angle' },
      { muscleId: 'scaleni',            tpId: 'TP2', location: 'Middle scalene' },
      { muscleId: 'multifidus',         tpId: 'TP1', location: 'Spinous process L4–L5' },
    ],
  },
  {
    id: 'arm_anterior',
    label: 'Arm — anterior / biceps region',
    region: 'arm',
    view: 'front',
    entries: [
      { muscleId: 'infraspinatus',           tpId: 'TP1', location: 'Medial fossa infraspinata' },
      { muscleId: 'subscapularis',           tpId: 'TP1', location: 'Axillary border' },
      { muscleId: 'scaleni',                 tpId: 'TP1', location: 'Anterior scalene' },
      { muscleId: 'pectoralis_minor',        tpId: 'TP1', location: 'Coracoid process' },
      { muscleId: 'biceps_brachii',     tpId: 'TP1', location: 'Mid-belly' },
      { muscleId: 'deltoideus',         tpId: 'TP1', location: 'Anterior deltoid' },
      { muscleId: 'pectoralis_major',   tpId: 'TP1', location: 'Clavicular head' },
      { muscleId: 'teres_minor',        tpId: 'TP1', location: 'Posterior axilla' },
      { muscleId: 'serratus_anterior',  tpId: 'TP1', location: 'Lateral thorax' },
    ],
  },
  {
    id: 'arm_posterior',
    label: 'Arm — posterior / triceps region',
    region: 'arm',
    view: 'back',
    entries: [
      { muscleId: 'scaleni',                 tpId: 'TP2', location: 'Middle scalene' },
      { muscleId: 'infraspinatus',           tpId: 'TP2', location: 'Lateral fossa infraspinata' },
      { muscleId: 'triceps_brachii',    tpId: 'TP1', location: 'Long head, mid-belly' },
      { muscleId: 'teres_major',        tpId: 'TP1', location: 'Posterior axilla' },
      { muscleId: 'deltoideus',         tpId: 'TP1', location: 'Posterior deltoid' },
      { muscleId: 'latissimus_dorsi',   tpId: 'TP1', location: 'Mid-belly, posterior axilla' },
    ],
  },
  {
    id: 'chest',
    label: 'Chest — anterior thorax',
    region: 'chest',
    view: 'front',
    entries: [
      { muscleId: 'pectoralis_major',        tpId: 'TP2', location: 'Sternal head' },
      { muscleId: 'pectoralis_major',        tpId: 'TP3', location: 'Abdominal fibres' },
      { muscleId: 'pectoralis_minor',        tpId: 'TP2', location: 'Costal mid-belly' },
      { muscleId: 'sternocleidomastoideus',  tpId: 'TP1', location: 'Sternal head' },
      { muscleId: 'scaleni',                 tpId: 'TP1', location: 'Anterior scalene' },
      { muscleId: 'serratus_anterior',  tpId: 'TP1', location: 'Lateral thorax' },
    ],
  },
  {
    id: 'thoracic_spine',
    label: 'Thoracic spine / mid-back',
    region: 'thoracic',
    view: 'back',
    entries: [
      { muscleId: 'erector_spinae',          tpId: 'TP2', location: 'Thoracic, T6–T9' },
      { muscleId: 'multifidus',              tpId: 'TP1', location: 'Spinous process L4–L5' },
      { muscleId: 'rhomboids',               tpId: 'TP1', location: 'Medial scapular border' },
      { muscleId: 'serratus_anterior',  tpId: 'TP1', location: 'Lateral thorax' },
      { muscleId: 'latissimus_dorsi',   tpId: 'TP1', location: 'Mid-belly, posterior axilla' },
      { muscleId: 'trapezius_asc',      tpId: 'TP1', location: 'Inferior scapular angle' },
    ],
  },
  {
    id: 'lumbar',
    label: 'Lumbar / low back',
    region: 'lumbar',
    view: 'back',
    entries: [
      { muscleId: 'erector_spinae',          tpId: 'TP1', location: 'Lumbar, L1–L3' },
      { muscleId: 'multifidus',              tpId: 'TP1', location: 'Spinous process L4–L5' },
      { muscleId: 'quadratus_lumborum',      tpId: 'TP1', location: 'Lateral border, iliac crest' },
      { muscleId: 'quadratus_lumborum',      tpId: 'TP2', location: 'Medial border, transverse processes' },
      { muscleId: 'iliopsoas',               tpId: 'TP1', location: 'Iliac fossa' },
      { muscleId: 'gluteus_medius',          tpId: 'TP1', location: 'Posterior iliac crest' },
      { muscleId: 'rectus_abdominis',   tpId: 'TP1', location: 'Upper belly' },
    ],
  },
  {
    id: 'sacral_gluteal',
    label: 'Sacrum / gluteal region',
    region: 'hip',
    view: 'back',
    entries: [
      { muscleId: 'quadratus_lumborum',      tpId: 'TP1', location: 'Lateral border, iliac crest' },
      { muscleId: 'gluteus_maximus',         tpId: 'TP1', location: 'Gluteal bulk' },
      { muscleId: 'gluteus_medius',          tpId: 'TP1', location: 'Posterior iliac crest' },
      { muscleId: 'piriformis',              tpId: 'TP1', location: 'Piriformis belly' },
      { muscleId: 'erector_spinae',          tpId: 'TP1', location: 'Lumbar, L1–L3' },
    ],
  },
  {
    id: 'hip_lateral',
    label: 'Hip — lateral / greater trochanter',
    region: 'hip',
    view: 'back',
    entries: [
      { muscleId: 'gluteus_medius',          tpId: 'TP1', location: 'Posterior iliac crest' },
      { muscleId: 'tensor_fasciae_latae',    tpId: 'TP1', location: 'Mid-belly, lateral thigh' },
      { muscleId: 'piriformis',              tpId: 'TP1', location: 'Piriformis belly' },
      { muscleId: 'quadratus_lumborum',      tpId: 'TP1', location: 'Lateral border' },
      { muscleId: 'gluteus_minimus',    tpId: 'TP1', location: 'Posterior belly, ilium' },
      { muscleId: 'gluteus_maximus',    tpId: 'TP1', location: 'Gluteal bulk' },
    ],
  },
  {
    id: 'thigh_anterior',
    label: 'Thigh — anterior / quadriceps',
    region: 'thigh',
    view: 'front',
    entries: [
      { muscleId: 'rectus_femoris',          tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'iliopsoas',               tpId: 'TP1', location: 'Iliac fossa' },
      { muscleId: 'tensor_fasciae_latae',    tpId: 'TP1', location: 'Mid-belly' },
      { muscleId: 'vastus_lateralis',   tpId: 'TP1', location: 'Lateral mid-belly' },
      { muscleId: 'vastus_medialis',    tpId: 'TP1', location: 'Medial mid-belly' },
      { muscleId: 'adductor_longus',    tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'adductor_magnus',    tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'sartorius',          tpId: 'TP1', location: 'Anteromedial thigh' },
    ],
  },
  {
    id: 'thigh_posterior',
    label: 'Thigh — posterior / hamstrings',
    region: 'thigh',
    view: 'back',
    entries: [
      { muscleId: 'hamstrings',              tpId: 'TP1', location: 'Mid-belly, biceps femoris' },
      { muscleId: 'gluteus_maximus',         tpId: 'TP1', location: 'Gluteal bulk' },
      { muscleId: 'piriformis',              tpId: 'TP1', location: 'Piriformis belly' },
      { muscleId: 'gluteus_minimus',    tpId: 'TP1', location: 'Posterior belly, ilium' },
    ],
  },
  {
    id: 'knee_anterior',
    label: 'Knee — anterior',
    region: 'knee',
    view: 'front',
    entries: [
      { muscleId: 'rectus_femoris',          tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'vastus_lateralis',   tpId: 'TP1', location: 'Lateral mid-belly' },
      { muscleId: 'vastus_medialis',    tpId: 'TP1', location: 'Medial mid-belly' },
      { muscleId: 'tensor_fasciae_latae', tpId: 'TP1', location: 'Mid-belly, lateral thigh' },
      { muscleId: 'adductor_longus',    tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'gracilis',           tpId: 'TP1', location: 'Mid-belly' },
    ],
  },
  {
    id: 'knee_posterior',
    label: 'Knee — posterior / popliteal',
    region: 'knee',
    view: 'back',
    entries: [
      { muscleId: 'hamstrings',              tpId: 'TP1', location: 'Distal belly, popliteal fossa' },
      { muscleId: 'gastrocnemius',           tpId: 'TP1', location: 'Proximal medial belly' },
      { muscleId: 'soleus',             tpId: 'TP1', location: 'Proximal soleus belly' },
    ],
  },
  {
    id: 'lower_leg_anterior',
    label: 'Lower leg — anterior / shin',
    region: 'lower_leg',
    view: 'front',
    entries: [
      { muscleId: 'tibialis_anterior',       tpId: 'TP1', location: 'Mid-belly, anterior shin' },
      { muscleId: 'peroneus_longus',         tpId: 'TP1', location: 'Proximal belly, fibular head' },
      { muscleId: 'peroneus_brevis',         tpId: 'TP1', location: 'Mid-belly, lateral fibula' },
    ],
  },
  {
    id: 'lower_leg_posterior',
    label: 'Lower leg — posterior / calf',
    region: 'lower_leg',
    view: 'back',
    entries: [
      { muscleId: 'gastrocnemius',           tpId: 'TP1', location: 'Medial belly' },
      { muscleId: 'soleus',                  tpId: 'TP1', location: 'Proximal soleus belly' },
      { muscleId: 'gluteus_minimus',         tpId: 'TP1', location: 'Posterior belly, ilium' },
      { muscleId: 'hamstrings',         tpId: 'TP1', location: 'Mid-belly, biceps femoris' },
    ],
  },
  {
    id: 'foot_ankle_anterior',
    label: 'Foot / ankle — anterior',
    region: 'foot',
    view: 'front',
    entries: [
      { muscleId: 'tibialis_anterior',       tpId: 'TP1', location: 'Distal belly' },
      { muscleId: 'peroneus_longus',         tpId: 'TP1', location: 'Proximal belly, fibular head' },
      { muscleId: 'peroneus_brevis',         tpId: 'TP1', location: 'Mid-belly, lateral fibula' },
    ],
  },
  {
    id: 'foot_ankle_posterior',
    label: 'Foot / ankle — posterior / heel',
    region: 'foot',
    view: 'back',
    entries: [
      { muscleId: 'gastrocnemius',           tpId: 'TP1', location: 'Medial belly' },
      { muscleId: 'soleus',                  tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'peroneus_longus',    tpId: 'TP1', location: 'Proximal belly, fibular head' },
      { muscleId: 'peroneus_brevis',    tpId: 'TP1', location: 'Mid-belly, lateral fibula' },
    ],
  },
  {
    id: 'face_jaw',
    label: 'Face / Jaw / Sinuses',
    region: 'face',
    view: 'front',
    entries: [
      { muscleId: 'masseter',          tpId: 'TP1', location: 'Superficial belly, cheek' },
      { muscleId: 'masseter',          tpId: 'TP2', location: 'Deep belly, near ear' },
      { muscleId: 'temporalis',        tpId: 'TP1', location: 'Anterior temporal' },
      { muscleId: 'temporalis',        tpId: 'TP2', location: 'Mid temporal' },
      { muscleId: 'lateral_pterygoid', tpId: 'TP1', location: 'Belly, infratemporal fossa' },
      { muscleId: 'medial_pterygoid',  tpId: 'TP1', location: 'Belly, medial' },
      { muscleId: 'sternocleidomastoideus', tpId: 'TP1', location: 'Sternal head' },
    ],
  },
  {
    id: 'elbow_anterior',
    label: 'Elbow — anterior / medial epicondyle',
    region: 'elbow',
    view: 'front',
    entries: [
      { muscleId: 'biceps_brachii',    tpId: 'TP1', location: 'Mid-belly' },
      { muscleId: 'forearm_flexors',   tpId: 'TP1', location: 'Proximal belly, medial forearm' },
      { muscleId: 'pectoralis_major',  tpId: 'TP1', location: 'Clavicular head' },
    ],
  },
  {
    id: 'elbow_posterior',
    label: 'Elbow — posterior / lateral epicondyle',
    region: 'elbow',
    view: 'back',
    entries: [
      { muscleId: 'forearm_extensors', tpId: 'TP1', location: 'Proximal belly, extensor mass' },
      { muscleId: 'triceps_brachii',   tpId: 'TP1', location: 'Long head, mid-belly' },
      { muscleId: 'supraspinatus',     tpId: 'TP1', location: 'Mid-belly, supraspinous fossa' },
      { muscleId: 'latissimus_dorsi',  tpId: 'TP1', location: 'Mid-belly, posterior axilla' },
    ],
  },
  {
    id: 'wrist_hand_anterior',
    label: 'Wrist / Palm / Fingers — anterior',
    region: 'wrist_hand',
    view: 'front',
    entries: [
      { muscleId: 'forearm_flexors',   tpId: 'TP1', location: 'Proximal belly, medial forearm' },
      { muscleId: 'forearm_flexors',   tpId: 'TP2', location: 'Distal belly, wrist' },
      { muscleId: 'subscapularis',     tpId: 'TP1', location: 'Axillary border' },
    ],
  },
  {
    id: 'wrist_hand_posterior',
    label: 'Wrist / Dorsum / Fingers — posterior',
    region: 'wrist_hand',
    view: 'back',
    entries: [
      { muscleId: 'forearm_extensors', tpId: 'TP1', location: 'Proximal belly, extensor mass' },
      { muscleId: 'forearm_extensors', tpId: 'TP2', location: 'Distal belly' },
      { muscleId: 'triceps_brachii',   tpId: 'TP1', location: 'Long head, mid-belly' },
      { muscleId: 'latissimus_dorsi',  tpId: 'TP1', location: 'Mid-belly, posterior axilla' },
    ],
  },
  {
    id: 'abdomen_region',
    label: 'Abdomen',
    region: 'abdomen',
    view: 'front',
    entries: [
      { muscleId: 'rectus_abdominis',  tpId: 'TP1', location: 'Upper belly' },
      { muscleId: 'rectus_abdominis',  tpId: 'TP2', location: 'Lower belly' },
      { muscleId: 'external_oblique',  tpId: 'TP1', location: 'Lateral belly' },
      { muscleId: 'iliopsoas',         tpId: 'TP1', location: 'Iliac fossa' },
    ],
  },
  {
    id: 'groin_inner_thigh',
    label: 'Groin / Inner thigh',
    region: 'hip_groin',
    view: 'front',
    entries: [
      { muscleId: 'adductor_longus',   tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'adductor_magnus',   tpId: 'TP1', location: 'Proximal belly' },
      { muscleId: 'gracilis',          tpId: 'TP1', location: 'Mid-belly' },
      { muscleId: 'iliopsoas',         tpId: 'TP1', location: 'Iliac fossa' },
      { muscleId: 'external_oblique',  tpId: 'TP1', location: 'Inguinal region' },
      { muscleId: 'rectus_abdominis',   tpId: 'TP2', location: 'Lower belly' },
      { muscleId: 'adductor_magnus',    tpId: 'TP2', location: 'Distal belly, medial knee' },
      { muscleId: 'vastus_medialis',    tpId: 'TP1', location: 'Medial mid-belly' },
    ],
  },
];

// Group zones by region for display
export const REGION_LABELS: Record<string, string> = {
  head:       'Head',
  neck:       'Neck',
  shoulder:   'Shoulder',
  arm:        'Arm',
  chest:      'Chest',
  thoracic:   'Thoracic / Mid-back',
  lumbar:     'Lumbar / Low back',
  hip:        'Hip / Gluteal',
  thigh:      'Thigh',
  knee:       'Knee',
  lower_leg:   'Lower leg',
  foot:        'Foot / Ankle',
  face:        'Face / Jaw',
  elbow:       'Elbow',
  wrist_hand:  'Wrist / Hand',
  abdomen:     'Abdomen',
  hip_groin:   'Groin / Inner thigh',
};
